### PR TITLE
enable github installs

### PR DESCRIPTION
**Pull request by ngokevin**

### CODE REVIEW

**Comment by joliss** [comment]
Interesting! I think this probably needs some improvements before we can merge it:
- I think if we're able to install a package, we should also be able to access it programmatically with `multidep` (like with `multidepRequire`).
- I don't really like the `[URL, path]` array syntax. I'm thinking that once we can access the package programmatically, the user doesn't even need to be able to specify a path, so `multidep` can just generate a path from the URL (replacing slashes with underscores, or something like that). So maybe a plain string is good enough - we could tell versions (`'1.0.0'`) from URLs or GitHub names (`'username/package'`) by checking if the string contains a slash.

What do you think?

**Comment by ngokevin** [comment]
Alright yeah, this was mostly a quick hack of least resistance for my use case.

So if we install `user/brocolli#hello`, it should output to `multidep/brocolli-hello`?

**Comment by joliss** [comment]
The most important thing is that we don't have multiple URLs clashing accidentally. I'm fairly indifferent about _how_ we make sure this doesn't happen.

By the way, if you check `npm install --help`, it also allows full `git://` URLs, so it seems that we're allowing both. (This is why I keep saying "URLs" -- the GitHub `user/repo#branch` syntax is basically just an abbreviation.) We should probably document this too.

**Comment by joliss** [comment]
So like I mentioned, I don't think this is usable enough to mergeable as it is. I'm closing this, but if you want to have another go, let me know and I can reopen.

**Pull request closed without merging**
